name: tic_tac_boom
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_tts: ^4.0.2
  go_router: ^14.1.4
  google_fonts: ^5.0.0
  http: ^1.2.0
  provider: ^6.1.2
  speech_to_text: ^6.6.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
